### ISSUE TITLE
INFO logs visible

### ISSUE THREAD

**Issue by ichoosetoaccept** [tumf/mcp-text-editor#2]
Hi

I came here to report this:
![CleanShot 2024-12-22 at 20 55 11@2x](https://github.com/user-attachments/assets/35a40d8f-98ef-46cb-8a6c-fbab7f9bbf30)

The server is working fine, it looks like, but it's printing INFO messages here. I see you already released 1.0.2 which mentions removing unexpected printing of logs.. 

Is 1.0.2 not published to NPM yet or is this an unrelated issue?

Thanks!

**Comment by tumf** [comment]
Thaks info .
the v1.0.2 has been released already before you reporeted 🤔 
https://pypi.org/project/mcp-text-editor/

if you have a chance, please chack with  version tag such like as `uvx mcp-text-editor@v1.0.2`
